import Html exposing (beginnerProgram, div, a, text, nav, ul, li, i)
import Html.Events exposing (onClick)
import Html.Attributes exposing (rel, class, href, rel, media)

main =
  beginnerProgram { model = 0, view = view, update = update }

view model =
  div [ class "wrapper" ]
    [ Html.node "link" [ rel "stylesheet", href "https://cdnjs.cloudflare.com/ajax/libs/normalize/4.2.0/normalize.min.css" ] []
    , Html.node "link" [ rel "stylesheet", href "stylesheets/main.css", media "screen, projection" ] []
    , Html.node "link" [ rel "stylesheet", href "https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" ] []
    , div [ class "navbar" ]
      [ a [ class "logo", href "#" ]
        [ text "DEV-KIT" ]
      , a [ class "menu", href "#" ]
        [ text "Menu" ]
      , nav [ class "prim-nav" ]
        [ ul []
          [ li []
            [ a [ href "#" ]
              [ text "Home" ]
            ]
          , li []
            [ a [ href "#" ]
              [ text "About" ]
            ]
          , li []
            [ a [ href "#" ]
              [ text "Pricing" ]
            ]
          , li []
            [ a [ href "#" ]
              [ text "Partners" ]
            ]
          , li []
            [ a [ href "#" ]
              [ text "Articles" ]
            , li []
              [ a [ href "#" ]
                [ text "Contact" ]
              ]
            , li [ class "social" ]
              [ a [ href "#" ]
                [ i [ class "fa fa-facebook" ]
                  []
                ]
              ]
            , li [ class "social" ]
              [ a [ href "#" ]
                [ i [ class "fa fa-twitter" ]
                  []
                ]
              ]
            , li [ class "social" ]
              [ a [ href "#" ]
                [ i [ class "fa fa-instagram" ]
                  []
                ]
              ]
            , li [ class "social" ]
              [ a [ href "#" ]
                [ i [ class "fa fa-pinterest" ]
                  []
                ]
              ]
            ]
          ]
        ]
      ]
    ]

type Msg = Increment | Decrement

update msg model = model
